project:
  type: website

website:
  title: "CPH 565 Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/thedbcooper/Bayesian-course-CPH565

format:
  html:
    theme: cosmo
    css: styles.css
